
# dataset info
dataset_name: "EUVP" 
dataset_path: "/kaggle/input/euvp-dataset/Paired"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 1000 # steps
ckpt_interval: 1  # epochs # Originally 20



 
