
dataset_name: "EUVP" 
dataset_path: "/kaggle/input/euvp-dataset/EUVP/Paired"
#input_dir: /kaggle/working/UIE/data
#input_name: col.jpg
nfc_init: 64
min_nfc_init: 32
ker_size: 3
num_layer: 5
stride: 1
noise_amp_init: 0.1
scale_factor: 0.75
scale1: 1.0
stop_scale: 5
lr_g: 0.0005
lr_d: 0.0005
beta1: 0.5
niter: 2000
nc_z: 3
nc_im: 3
lambda_grad: 0.1
not_cuda: false
